### ISSUE TITLE
helpful-callable hangs on hippie-expand with smartparens required

### ISSUE THREAD

**Issue by 6AA4FD** [Wilfred/helpful#179] opened 2018-12-26 07:18 UTC
with helpful and smartparens loaded, emacs hangs after evaling `(helpful-callable 'hippie-expand)`
these logs are from emacs --version 27.0.50 -Q
the only other code run in the instance was adding melpa and installing the packages

i'm not too good at bug reports, so please tell me if i can help more
 
[btrace.txt](https://github.com/Wilfred/helpful/files/2709689/btrace.txt)
[profile.txt](https://github.com/Wilfred/helpful/files/2709697/profile.txt)

EDIT: i realize that the profile file could be hard to read, so here's an image
![profile_img](https://user-images.githubusercontent.com/12578560/50436663-dd769500-089b-11e9-89f6-d9db396b844f.jpg)

**Comment by Wilfred** [comment] 2018-12-29 10:47
I can't reproduce this on Emacs 26.1. Can you?

Looking at the backtrace, I wonder if `find-function-advised-original` is behaving differently in Emacs 27. What happens if you run the following?

```
M-x ielm
(find-function-advised-original 'hippie-expand)
```

Does it hang, or does it show output?

**Comment by 6AA4FD** [comment] 2018-12-30 04:43
it outputs `(autoload "hippie-exp" 1203003 t nil)` on 26 and something similar on 27
and `(helpful-callable 'hippie-expand)` also doesn't fail on 26
i want to mention that it's perfectly cool if you don't want to bother with supporting 27 yet, though i like your software and would obviously prefer it work better on my setup

**Comment by 6AA4FD** [comment] 2019-01-01 03:39
i get the same behaviour on my end

**Comment by Wilfred** [comment] 2019-03-03 22:47
I think this is probably a duplicate of #117, which is now fixed :)

Let me know if not.

**Closed by Wilfred** 2019-03-03 22:47 UTC

**Comment by hlissner** [comment] 2020-01-07 06:49
This appears to still be a problem on Emacs 26.3. `helpful-callable` hangs indefinitely (or so it seems) on any function that has been autoloaded and advised.

It can be reproduced with the following on vanilla Emacs:

```elisp
(require 'helpful)
;; I've tested on functions and commands that exist as well
(autoload 'x "x" nil t)
(defun myadvice (&rest args)
  (apply orig-fn args))
;; I've tried :after, :before, and :override with the same results
(advice-add 'x :override #'myadvice)
(helpful-callable 'x)
```

With `debug-on-quit` on, I've produced this backtrace after waiting a minute or so:

```
Debugger entered--Lisp error: (quit)
  advice--p(#f(advice-wrapper :around nil myadvice))
  advice--cd*r(#f(advice-wrapper :around nil myadvice))
  find-function-advised-original(org-clock-in)
  find-function-library(org-clock-in)
  helpful--definition(org-clock-in t)
  helpful-update()
  helpful-callable(org-clock-in)
  (progn (require (quote helpful)) (autoload (quote org-clock-in) "org-clock" nil t) (defalias (quote myadvice) (function (lambda (orig-fn &rest args) (apply orig-fn args)))) (advice-add (quote org-clock-in) :around (function myadvice)) (setq debug-on-quit t) (helpful-callable (quote org-clock-in)))
  (unwind-protect (progn (require (quote helpful)) (autoload (quote org-clock-in) "org-clock" nil t) (defalias (quote myadvice) (function (lambda (orig-fn &rest args) (apply orig-fn args)))) (advice-add (quote org-clock-in) :around (function myadvice)) (setq debug-on-quit t) (helpful-callable (quote org-clock-in))) (delete-file "/tmp/doom-sandbox-TSLf3x"))
  eval-buffer(#<buffer  *load*> nil "/tmp/doom-sandbox-TSLf3x" nil t)  ; Reading at buffer position 20133
  load-with-code-conversion("/tmp/doom-sandbox-TSLf3x" "/tmp/doom-sandbox-TSLf3x" nil t)
  load("/tmp/doom-sandbox-TSLf3x" nil t)
  command-line-1(("-l" "/tmp/doom-sandbox-TSLf3x"))
  command-line()
  normal-top-level()
```

It appears to be trapped in `advice--cd*r`:

```elisp
;; in nadvice.el.gz, L70
(defun advice--cd*r (f)
  (while (advice--p f)
    (setq f (advice--cdr f)))
  f)
```

I am on the latest commit of helpful: 982dd49

**Comment by hlissner** [comment] 2020-01-23 07:45
Should I open a new issue for this?

**Comment by Wilfred** [comment] 2020-03-23 02:40
Looks like #191 is the same issue, but thanks for the great repro!
