### ISSUE TITLE
helpful-key does not show the full information

### ISSUE THREAD

**Issue by in-in** [Wilfred/helpful#178] opened 2018-12-22 10:18 UTC
`M-x helpful-key <f6>`
Show this
```elisp
org-capture is an interactive function without a source file.

Signature
(org-capture &optional GOTO KEYS)
```
And Messages buffer says:
`helpful--format-docstring: Symbol’s value as variable is void: org-capture-mode-map`

At the same time, the output of `description-key` is good.
`M-x describe-key <f6>`

```elisp
<f6> runs the command org-capture (found in global-map), which is an
interactive autoloaded Lisp function.

It is bound to <f6>.

(org-capture &optional GOTO KEYS)

Capture something.

This will let you select a template from ‘org-capture-templates’, and
then file the newly captured information.  The text is immediately
inserted at the target location, and an indirect buffer is shown where
you can edit it.  Pressing ‘C-c C-c’ brings you back to the previous
state of Emacs, so that you can continue your work.

When called interactively with a ‘C-u’ prefix argument GOTO, don’t
capture anything, just go to the file/headline where the selected
template stores its notes.

With a ‘C-u C-u’ prefix argument, go to the last note stored.

When called with a ‘C-0’ (zero) prefix, insert a template at point.

When called with a ‘C-1’ (one) prefix, force prompting for a date when
a datetree entry is made.

ELisp programs can set KEYS to a string associated with a template
in ‘org-capture-templates’.  In this case, interactive selection
will be bypassed.

If ‘org-capture-use-agenda-date’ is non-nil, capturing from the
agenda will use the date at point as the default date.  Then, a
‘C-1’ prefix will tell the capture process to use the HH:MM time
of the day at point (if any) or the current HH:MM time.

```

My config file
```elisp
(use-package org
  :ensure t
  :bind (("C-c a" . org-agenda)
  ("<f6>" . org-capture)))

(use-package helpful
  :ensure t)
```

Emacs 26.1
helpful 0.15

**Comment by Wilfred** [comment] 2019-03-03 22:51
Duplicate of #117, which is now fixed :)

**Closed by Wilfred** 2019-03-03 22:51 UTC
