### ISSUE TITLE
Can't find functions defined in C code

### ISSUE THREAD

**Issue by mookid** [Wilfred/helpful#71] opened 2017-12-16 13:58 UTC
HI @Wilfred  and thanks for this package!

When calling `helpful-at-point` on (for instance) `mapconcat`, I get the error `"Can’t find library src/fns.c"`, while `xref-find-definitions` finds its way to the source.

**Comment by Wilfred** [comment] 2017-12-16 15:27
I think this is a duplicate of #65 -- please upgrade :)

**Closed by Wilfred** 2017-12-16 15:27 UTC

**Comment by mookid** [comment] 2017-12-16 17:03
confirmed, sorry for the noise!
