### ISSUE TITLE
Support C-h S (info-lookup-symbol) in helpful-mode

### ISSUE THREAD

**Issue by xuchunyang** [Wilfred/helpful#21] opened 2017-09-01 18:46 UTC
`C-h S` (`info-lookup-symbol`) is for searching Info manual base on the Major mode, for `helpful-mode`, since it's related to Emacs, `C-h S` should search Emacs-related info manuals, like `help-mode`.

Not sure about the correct way, but I found the following works for me.

~~~ emacs-lisp
(info-lookup-maybe-add-help
 :mode 'helpful-mode
 :regexp "[^][()`'‘’,:\" \t\n]+"
 :other-modes '(emacs-lisp-mode))

(info-lookup-maybe-add-help
 :mode 'elisp-refs-mode
 :regexp "[^][()`'‘’,:\" \t\n]+"
 :other-modes '(emacs-lisp-mode))
~~~

changed from (in the end of `info-look.el`)

~~~ emacs-lisp
(info-lookup-maybe-add-help
 :mode 'help-mode
 :regexp "[^][()`'‘’,:\" \t\n]+"
 :other-modes '(emacs-lisp-mode))
~~~

**Comment by Wilfred** [comment] 2017-09-05 21:32
I think this is duplicate of #7. I'd like to have something like:

```
Documentation
If COND yields non-nil, do BODY, else return nil.

When COND yields non-nil, eval BODY forms sequentially and return
value of last one, or nil if there are none.

[View in manual]
```

We would then only show the button if the symbol was available in the manual.

Does this meet your need? I've never seen `info-lookup-symbol` before, so I may have misunderstood.

**Comment by Wilfred** [comment] 2017-12-16 15:30
I believe this has been sorted by #7 and #32.

**Closed by Wilfred** 2017-12-16 15:30 UTC
